# Site
repository: heewonoweeh/heewonoweeh.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 윤희원(Heewon Yun)
title: Cloud Engineer
email: heewonoweeh@gmail.com
website: https://url.kr/ofa27k

# Dark Mode (true/false/never)
darkmode: false

minimal_mistakes_skin: default

# Social links
# twitter_username: facespics
github_username:  heewonoweeh
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: heewonoweeh
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: velog
  icon: fas fa-globe
  url: https://velog.io/@heewonoweeh
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  3년 차 클라우드 엔지니어로 Azure 기반의 서비스를 설계/개발/배포/운영하고 다양한 비즈니스 업무를 자동화한 경험이 있습니다.   
  <br>
  <h4><strong>저는 ___ 엔지니어입니다.</strong></h4>
  <mark style='background-color: #345f53'>#꼼꼼한</mark>, <mark style='background-color: #345f53'>#대응력 빠른</mark>, <mark style='background-color: #345f53'>#끈질긴</mark>   
  명확한 Input과 Output, Feedback을 바탕으로 일을 처리하는 것을 좋아합니다.    
  어떤 세부 사항도 간과하지 않고 살펴보며, 여러 예외적인 상황에 대응할 수 있도록 꼼꼼하게 준비하여 침착하게 해결할 수 있습니다.    
  <br>
  문제 해결을 위한 끈질김은 개발에도 똑같이 적용된다고 생각합니다.   
  확장성 및 성능 최적화된 아키텍처 구현을 위해 새로운 기술과 트렌드를 적극적으로 수용하고 업무에 활용할 수 있도록 노력하고 있습니다.   
  <br>
  <h4><strong>관심있는 분야는 ___ 입니다.</strong></h4>
  <mark style='background-color: #345f53'>#Multi Cloud</mark>, <mark style='background-color: #345f53'>#Cloud security</mark>, <mark style='background-color: #345f53'>#MSA</mark>, <mark style='background-color: #345f53'>#커뮤니케이션</mark>   
  - Multi Cloud 트렌드에 대응하기 위해 AWS 기반 보안 인증 시스템, 네트워크, 서버, 로드밸런서 등을 구축해 보았습니다.   
  - 다양한 언어나 프레임워크를 사용하는 마이크로 서비스 구축을 위한 쿠버네티스를 공부하고 있습니다.
  - 네트워킹 프로그램에 참여하여 직장 내뿐만 아니라 고객사와의 소통 방식에 대해 언제나 고민하고 있습니다.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 딕스코리아
        sub_title: '2021.01 ~ 2023.11'
        caption: Cloud Engineer
        description: | # this will include new lines to allow paragraphs
            - Azure 기반 Cloud 보안 아키텍처 설계
            - Azure Active Directory 기반 사용자 관리 API 개발
            - Azure App Service 기반 VDI 웹페이지 프론트엔드 / 백엔드 개발
            - Azure와 Microsoft Power Platform 활용한 기업 디지털 트랜스포메이션
            - 기존 프로젝트 유지보수 및 고도화

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 그룹웨어 전자결재<br>API 구축
        sub_title: 웅진씽크빅
        caption: 2023.05 ~ 2023.06
        description: | # this will include new lines to allow paragraphs
            <br>
            - 그룹웨어 전자결재 시스템 백엔드 개발
            - Azure AD 사용자 관리 자동화
            - 온-프레미스 AD 계정 정보 업데이트 API 개발
            - Azure Key Vault를 이용한 API URL, Function key 및 데이터베이스 연결 정보 보호 
            - **Skill Keywords**   
            <mark>Azure Functions</mark>, <mark style='background-color: #0366d6'>Azure Active Directory</mark>, <mark style='background-color: #0366d6'>Azure Key Vault</mark>, <mark style='background-color: #0366d6'>PowerShell</mark>, <mark>Azure Devops</mark>, <mark>Azure SQL</mark>,<br><mark>Microsoft Power Automate</mark>, <mark>Python</mark>
      
      - layout: left
        title: VDI 웹페이지<br>제작 및 고도화
        sub_title: 웅진씽크빅
        caption: 2021.11 ~ 2021.12, 2022.08 ~ 2022.09
        description: | # this will include new lines to allow paragraphs
            <br>
            - Azure App Service를 이용한 로컬 PC 원격 제어 웹페이지 제작
            - Django 기반 프론트엔드 / 백엔드 환경 구성 및 전체 기능 구현
            - Azure Key Vault를 이용한 웹사이트 내 민감 데이터(연결 문자열, 암호 등) 보호
            - Microsoft Graph API를 이용한 사용자 액세스 제어 기능 구현
            - WinRM을 사용하여 로컬 PC(Windows) 시작, 종료, 재부팅 기능 구현 
            - Azure Service Bus를 이용한 Azure Virtual Machine 생성 자동화
            - **Skill Keywords**   
            <mark>Azure App Service</mark>, <mark style='background-color: #0366d6'>Azure Key Vault</mark>, <mark style='background-color: #0366d6'>Microsoft Graph API</mark>, <mark style='background-color: #0366d6'>PowerShell</mark>, <mark style='background-color: #0366d6'>Azure Automation</mark>, <mark>Azure Service Bus</mark>,<br><mark>Azure VM</mark>, <mark>Azure Devops</mark>, <mark>Azure SQL</mark>, <mark>Django</mark>, <mark>Python</mark>, <mark>JavaScript</mark>, <mark>HTML/CSS</mark>
      
      - layout: left
        title: 법인카드 전표 생성<br>자동화 개발 및 고도화
        sub_title: 웅진씽크빅
        caption: 2021.06 ~ 2021.08, 2022.05 ~ 2022.06
        description: | # this will include new lines to allow paragraphs
            <br>
            - 서버리스 함수(Azure Functions)를 이용한 임시전표 생성 자동화
            - Azure Key Vault를 이용한 데이터베이스 연결 정보, 네이버웍스 API 키, 토큰 보호
            - Azure Functions를 이용한 액세스 토큰 유효성 검사 및 재발급 자동화
            - 자동화 프로세스 내에서 사용하기 위한 네이버웍스 운영 모듈 개발
            - 네이버웍스 API를 이용한 처리 결과 메시지 전송 기능 구현
            - 문제 발생 시 신속하게 대응하기 위한 오류 알림 기능 구현
            - **Skill Keywords**   
            <mark>Azure Functions</mark>, <mark style='background-color: #0366d6'>Azure Key Vault</mark>, <mark>Azure Devops</mark>, <mark>Azure SQL</mark>, <mark>Microsoft Power Automate</mark>, <mark>Python</mark>

      - layout: left
        title: 실시간 내/외부<br>중계 보고서 개발
        sub_title: 농협중앙회
        caption: 2023.01 ~ 2023.03
        description: | # this will include new lines to allow paragraphs
            <br>
            - 선관위 데이터를 활용한 실시간 투표/개표 현황 보고서 제작
            - 실시간 운영 상황 모니터링 및 장애 대응
            - 내부망 동작을 위한 Power Automate 자동화 시스템 환경 구축
            - 보고서용 데이터 전처리 자동화
            - Power Automate를 이용한 웹 크롤링 기능 구현
            - **Skill Keywords**   
            <mark>Microsoft Power Automate</mark>

      - layout: left
        title: 세금계산서 및 반출신고<br>업무 자동화
        sub_title: 네패스
        caption: 2022.10 ~ 2022.12
        description: | # this will include new lines to allow paragraphs
            - 내부망 동작을 위한 Power Automate 자동화 시스템 환경 구축
            - 고객사별 세금계산서 요청 알림 기능 구현
            - 접수된 인보이스를 토대로 반출신고 업무 자동화
            - **Skill Keywords**   
            <mark>Microsoft Power Automate</mark>

  - title: Certificate # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: '2023.10'
        description: '![az104](/images/az104.jpg){: width="50px" height="50px"} [AZ-104] Azure Administrator Associate '

      - layout: left
        title: '2023.08'
        description: '![az204](/images/az204.jpg){: width="50px" height="50px"} [AZ-204] Azure Developer Associate'

      - layout: left
        title: '2022.04'
        description: '![az900](/images/az900.jpg){: width="50px" height="50px"} [AZ-900] Azure Fundamentals'
        
  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 2016.03 ~ 2020.02
        description: 경기과학기술대학교 컴퓨터모바일융합과

      - layout: left
        title: 2012.03 ~ 2016.02
        description: 선일여자고등학교

  - title: ETC # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 2023.09 ~ 2023.10
        description: '[KMOOC] 클라우드 보안 엔지니어 양성과정'

      - layout: left
        title: '2023.09'
        description: '[GIT×Trend Micro] 정보보안 기초과정 프로그램'

      - layout: left
        title: '2023.08'
        description: '[KISIA] 온택트 융합보안(클라우드)'

      - layout: left
        title: '2023.07'
        description: '[WISET] 4th Seminar for Women in Cyber Security'

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

github: [metadata]